### PR TITLE
Replace abandoned crc16 with fastcrc

### PR DESCRIPTION
**Pull request by sonofmom**
This will establish compatibility with Python 3.10 (default python on Ubuntu 22.04 and other newer distros)

Not sure about update procedure, installation of fastcrc module should be ensured.

### CODE REVIEW

**Comment by awesome-doge** [comment]
I have tested it on my ubuntu 22.04 python 3.10.

I do not see the error message
It looks like the problem has been solved.


image



But there is still a small problem here.

- The status of the node
- Synchronisation status
- Hard disk usage
- Version number display

None of the above data is displayed.

截圖 2022-12-19 下午4 10 31

**Review by awesome-doge — APPROVED** [review]
I tested it with ubuntu 22.04 and python 3.10.

The test passed.

**Comment by sonofmom** [comment]
Hi @awesome-doge,

Local information is missing because parameter `validatorWalletName` was not set during installation because of the problem this PR fixes, you can return local display by issuing command 'set validatorWalletName validator_wallet_001' and restarting mytonctrl.

The versions will still not displayed because there is issue with git compatibility.

**Comment by Vasilesk** [comment]
Hello, will it be merged soon? 😅

**Pull request merged**
